"""Turn a build into the text of the files it produces.

Still pure: every function here returns a string, and nothing opens a file or
runs a command. Putting those strings on a disk is plan.py's decision and
writer.py's job, which is what keeps the hard part — deciding what should be
in these files — separable from the easy part.

The generated install script carries the compatibility engine's findings with
it, as comments. A warning that only ever appeared on a screen the user has
since closed is a warning that did not survive to the moment it mattered; one
sitting above the command it is about gets read by whoever runs the script.
"""

from __future__ import annotations

from datetime import date

import textwrap
from typing import Any, Mapping

from lsc import __version__, compat
from lsc.data.catalog import CATEGORIES
from lsc.models import Build, Issue
from lsc.safety import snapshots

# How wide a line inside a "#   " comment block may be before it stops being
# readable in an 80-column terminal, which is where a generated install script
# is most likely to be opened.
WRAP = 68


def package_list(build: Build) -> str:
    """Every package the build pulls in, grouped by the decision that added it.

    Grouping rather than flattening is deliberate: a bare list of ninety package
    names tells you nothing about why any of them is there.
    """
    lines = [
        "# Packages for " + build.name,
        "# Generated by Linux System Composer. Nothing here has been installed.",
        "",
    ]
    total = 0
    for category in CATEGORIES:
        component = category.get(build.selected_id(category.id))
        if component is None or not component.packages:
            continue
        lines.append(f"# {category.name}: {component.name}")
        lines.extend(component.packages)
        lines.append("")
        total += len(component.packages)

    lines.append(f"# {total} packages total")
    return "\n".join(lines)


def install_script(
    build: Build, hardware_profile: Mapping[str, Any] | None = None
) -> str:
    """The installation steps in dependency order, bottom of the stack upward.

    Written as a readable script rather than a clever one: someone should be
    able to read it and understand what the composer decided on their behalf.

    The hardware profile is optional and only sharpens the warnings that get
    embedded: without it, rules that depend on the machine stay unknown and
    are reported as unchecked rather than guessed at.
    """
    selections = {
        category.id: category.get(build.selected_id(category.id)) for category in CATEGORIES
    }

    def name_of(category_id: str) -> str:
        component = selections.get(category_id)
        return component.name if component else "none"

    filesystem = selections.get("filesystem")
    bootloader = selections.get("bootloader")

    lines = [
        "#!/usr/bin/env bash",
        "#",
        f"# {build.name} — generated {date.today().isoformat()}",
        "# Linux System Composer generated this. Read every line before running it.",
        "#",
        "#   base       " + name_of("base"),
        "#   kernel     " + name_of("kernel"),
        "#   bootloader " + name_of("bootloader"),
        "#   filesystem " + name_of("filesystem"),
        "#   gpu        " + name_of("gpu"),
        "#   display    " + name_of("display"),
        "#   desktop    " + name_of("desktop"),
        "#   audio      " + name_of("audio"),
        "#   security   " + name_of("security"),
        "",
        "set -euo pipefail",
        "",
        "# 1. Filesystem",
    ]

    if filesystem and filesystem.id == "btrfs":
        lines += [
            "mkfs.btrfs -L root /dev/sdX2",
            "mount /dev/sdX2 /mnt",
            "btrfs subvolume create /mnt/@",
            "btrfs subvolume create /mnt/@home",
            "btrfs subvolume create /mnt/@snapshots   # rollback target",
        ]
    elif filesystem:
        lines += [
            f"# {filesystem.name} root",
            "mount /dev/sdX2 /mnt",
        ]

    lines += ["", "# 2. Base system and kernel", "pacstrap -K /mnt \\"]
    for category_id in ("base", "kernel"):
        component = selections.get(category_id)
        if component:
            for package in component.packages:
                lines.append(f"    {package} \\")
    lines.append("    vim")

    lines += ["", "# 3. Everything above the kernel", "arch-chroot /mnt pacman -S --needed \\"]
    for category_id in ("filesystem", "gpu", "display", "desktop", "audio", "security"):
        component = selections.get(category_id)
        if component:
            for package in component.packages:
                lines.append(f"    {package} \\")
    lines.append("    # end of package list")

    lines += ["", "# 4. Bootloader"]
    if bootloader and bootloader.id == "systemd-boot":
        lines.append("arch-chroot /mnt bootctl install")
    elif bootloader and bootloader.id == "grub":
        lines += [
            "arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot",
            "arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg",
        ]
    elif bootloader:
        lines.append(f"# install {bootloader.name} — see its documentation")

    # Choices that only take effect through a kernel command line parameter are
    # exactly the kind of hidden step this project exists to stop people missing.
    kernel_params = _kernel_parameters(build)
    if kernel_params:
        lines += ["", "# 5. Kernel parameters required by these choices"]
        for param, reason in kernel_params:
            lines.append(f"#   {param}    # {reason}")

    # Milestone 5 reaches into the generated output here. Whether this system
    # will be able to undo a bad update is decided by the filesystem chosen
    # several screens ago, and the install script is the last place that
    # consequence can still be pointed out to whoever runs it.
    lines += ["", "# 6. Recovering from a bad update"]
    advice = snapshots.advise(build)
    lines.append(advice.as_script_comment())
    if advice.packages:
        lines.append("arch-chroot /mnt pacman -S --needed " + " ".join(advice.packages))

    warnings = _warnings(build, hardware_profile)
    if warnings:
        lines += ["", "# 7. What the compatibility engine wants you to know", "#"]
        for number, issue in enumerate(warnings, start=1):
            lines.append(f"#   {number}. {issue.title}")
            for sentence in textwrap.wrap(issue.detail, WRAP):
                lines.append(f"#      {sentence}")
            for sentence in textwrap.wrap(f"Fix: {issue.fix}", WRAP):
                lines.append(f"#      {sentence}")
            lines.append("#")

    return "\n".join(lines)


def manifest(build: Build) -> str:
    """The build as a file you could commit, share, or feed back in.

    This is the reproducibility promise from the README in its smallest honest
    form: the whole system described in a few lines of TOML.
    """
    lines = [
        "# Linux System Composer build manifest",
        f'name = "{build.name}"',
        f'generated = "{date.today().isoformat()}"',
        # Read from the package rather than written out, because a version
        # string copied into a generated file is a version string that will
        # eventually be wrong in a file someone is relying on to reproduce
        # a system.
        f'composer_version = "{__version__}"',
        "",
        "[stack]",
    ]
    for category in CATEGORIES:
        component_id = build.selected_id(category.id)
        value = f'"{component_id}"' if component_id else "# unset"
        lines.append(f"{category.id} = {value}")

    lines += ["", "[meta]", "# What each choice was, in words, for whoever reads this later."]
    for category in CATEGORIES:
        component = category.get(build.selected_id(category.id))
        if component:
            lines.append(f"# {category.id}: {component.name} — {component.summary}")

    return "\n".join(lines)


def _warnings(
    build: Build, hardware_profile: Mapping[str, Any] | None
) -> list[Issue]:
    """The warnings this build carries.

    Errors are deliberately absent rather than filtered for tidiness: preflight
    refuses to write a build that has any, so a generated script cannot contain
    one. Info-level notes are left out because the script would stop being
    readable, and they are not the things that break a machine at midnight.
    """
    issues = compat.check(build, hardware_profile)
    return [issue for issue in issues if issue.severity == "warning"]


def _kernel_parameters(build: Build) -> list[tuple[str, str]]:
    """Kernel command line parameters implied by the current selections."""
    params: list[tuple[str, str]] = []
    selected = build.selected_ids()

    if {"nvidia", "nvidia-open"} & selected:
        params.append(
            ("nvidia_drm.modeset=1", "required before any Wayland compositor will start")
        )
    if "apparmor" in selected or "hardened" in selected:
        params.append(
            ("lsm=landlock,lockdown,yama,integrity,apparmor,bpf", "enables AppArmor at boot")
        )
    if "zfs" in selected:
        params.append(("zfs=zroot", "tells the initramfs which pool to import"))
    return params


def render(
    kind: str, build: Build, hardware_profile: Mapping[str, Any] | None = None
) -> str:
    """Dispatch used by the Export screen's file switcher and by plan.py."""
    if kind == "packages":
        return package_list(build)
    if kind == "install":
        return install_script(build, hardware_profile)
    if kind == "manifest":
        return manifest(build)
    return f"Unknown export: {kind}"
