"""Turn a build into the text of the files it would produce.

Preview only. These functions return strings; nothing here opens a file, runs a
command, or touches the system. Milestone 4 adds writing them out; the hard
part — deciding what should be in them — is what this module is for.
"""

from __future__ import annotations

from datetime import date

from lsc.data.catalog import CATEGORIES, COMPONENTS_BY_ID
from lsc.models import Build


def package_list(build: Build) -> str:
    """Every package the build pulls in, grouped by the decision that added it.

    Grouping rather than flattening is deliberate: a bare list of ninety package
    names tells you nothing about why any of them is there.
    """
    lines = [
        "# Packages for " + build.name,
        "# Generated by Linux System Composer — preview only, nothing installed.",
        "",
    ]
    total = 0
    for category in CATEGORIES:
        component = category.get(build.selected_id(category.id))
        if component is None or not component.packages:
            continue
        lines.append(f"# {category.name}: {component.name}")
        lines.extend(component.packages)
        lines.append("")
        total += len(component.packages)

    lines.append(f"# {total} packages total")
    return "\n".join(lines)


def install_script(build: Build) -> str:
    """The installation steps in dependency order, bottom of the stack upward.

    Written as a readable script rather than a clever one: someone should be
    able to read it and understand what the composer decided on their behalf.
    """
    selections = {
        category.id: category.get(build.selected_id(category.id)) for category in CATEGORIES
    }

    def name_of(category_id: str) -> str:
        component = selections.get(category_id)
        return component.name if component else "none"

    filesystem = selections.get("filesystem")
    bootloader = selections.get("bootloader")

    lines = [
        "#!/usr/bin/env bash",
        "#",
        f"# {build.name} — generated {date.today().isoformat()}",
        "# Linux System Composer — PREVIEW. Read every line before running it.",
        "#",
        "#   base       " + name_of("base"),
        "#   kernel     " + name_of("kernel"),
        "#   bootloader " + name_of("bootloader"),
        "#   filesystem " + name_of("filesystem"),
        "#   gpu        " + name_of("gpu"),
        "#   display    " + name_of("display"),
        "#   desktop    " + name_of("desktop"),
        "#   audio      " + name_of("audio"),
        "#   security   " + name_of("security"),
        "",
        "set -euo pipefail",
        "",
        "# 1. Filesystem",
    ]

    if filesystem and filesystem.id == "btrfs":
        lines += [
            "mkfs.btrfs -L root /dev/sdX2",
            "mount /dev/sdX2 /mnt",
            "btrfs subvolume create /mnt/@",
            "btrfs subvolume create /mnt/@home",
            "btrfs subvolume create /mnt/@snapshots   # rollback target",
        ]
    elif filesystem:
        lines += [
            f"# {filesystem.name} root",
            "mount /dev/sdX2 /mnt",
        ]

    lines += ["", "# 2. Base system and kernel", "pacstrap -K /mnt \\"]
    for category_id in ("base", "kernel"):
        component = selections.get(category_id)
        if component:
            for package in component.packages:
                lines.append(f"    {package} \\")
    lines.append("    vim")

    lines += ["", "# 3. Everything above the kernel", "arch-chroot /mnt pacman -S --needed \\"]
    for category_id in ("filesystem", "gpu", "display", "desktop", "audio", "security"):
        component = selections.get(category_id)
        if component:
            for package in component.packages:
                lines.append(f"    {package} \\")
    lines.append("    # end of package list")

    lines += ["", "# 4. Bootloader"]
    if bootloader and bootloader.id == "systemd-boot":
        lines.append("arch-chroot /mnt bootctl install")
    elif bootloader and bootloader.id == "grub":
        lines += [
            "arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot",
            "arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg",
        ]
    elif bootloader:
        lines.append(f"# install {bootloader.name} — see its documentation")

    # Choices that only take effect through a kernel command line parameter are
    # exactly the kind of hidden step this project exists to stop people missing.
    kernel_params = _kernel_parameters(build)
    if kernel_params:
        lines += ["", "# 5. Kernel parameters required by these choices"]
        for param, reason in kernel_params:
            lines.append(f"#   {param}    # {reason}")

    return "\n".join(lines)


def manifest(build: Build) -> str:
    """The build as a file you could commit, share, or feed back in.

    This is the reproducibility promise from the README in its smallest honest
    form: the whole system described in a few lines of TOML.
    """
    lines = [
        "# Linux System Composer build manifest",
        f'name = "{build.name}"',
        f'generated = "{date.today().isoformat()}"',
        'composer_version = "0.2.0"',
        "",
        "[stack]",
    ]
    for category in CATEGORIES:
        component_id = build.selected_id(category.id)
        value = f'"{component_id}"' if component_id else "# unset"
        lines.append(f"{category.id} = {value}")

    lines += ["", "[meta]", "# What each choice was, in words, for whoever reads this later."]
    for category in CATEGORIES:
        component = category.get(build.selected_id(category.id))
        if component:
            lines.append(f"# {category.id}: {component.name} — {component.summary}")

    return "\n".join(lines)


def _kernel_parameters(build: Build) -> list[tuple[str, str]]:
    """Kernel command line parameters implied by the current selections."""
    params: list[tuple[str, str]] = []
    selected = build.selected_ids()

    if {"nvidia", "nvidia-open"} & selected:
        params.append(
            ("nvidia_drm.modeset=1", "required before any Wayland compositor will start")
        )
    if "apparmor" in selected or "hardened" in selected:
        params.append(
            ("lsm=landlock,lockdown,yama,integrity,apparmor,bpf", "enables AppArmor at boot")
        )
    if "zfs" in selected:
        params.append(("zfs=zroot", "tells the initramfs which pool to import"))
    return params


def render(kind: str, build: Build) -> str:
    """Dispatch used by the Export screen's file switcher."""
    if kind == "packages":
        return package_list(build)
    if kind == "install":
        return install_script(build)
    if kind == "manifest":
        return manifest(build)
    return f"Unknown export: {kind}"
